feat: #2524 SMB App should redirect to Users route from root path
reapit/foundations pull request #2529
Opened 2020-08-31 03:29 UTC by ant066

# Pull request checklist

## Does this close any currently open issues?

fixes: #2524

**Please check if your PR fulfills the following requirements:**

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint`) has passed locally and any fixes were made for failures
- [x] Test (`yarn test`) has passed locally and any fixes were made for failures

## Pull request type

**Please check the type of change your PR introduces:**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #2524

## What is the new behavior?
SMB App should redirect to Users route from root path 
## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-08-31 06:54 UTC, phmngocnghia approved these changes

2020-08-31 10:23 UTC, nphivu414 approved these changes

2020-09-01 07:34 UTC, tanphamhaiduong requested changes
Pls ref Geo-diary for fix this problem

2020-09-01 08:40 UTC, tanphamhaiduong approved these changes

2020-09-01 08:56 UTC, merged