feat: #2616 migrate button to elements v2
reapit/foundations pull request #2692
Opened 2020-09-14 09:18 UTC by vuhuucuong

# Pull request checklist

## Does this close any currently open issues?

fixes: #2616

**Please check if your PR fulfills the following requirements:**

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint`) has passed locally and any fixes were made for failures
- [x] Test (`yarn test`) has passed locally and any fixes were made for failures

## Pull request type

**Please check the type of change your PR introduces:**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #2616

## What is the new behavior?

- Add `Button` and `ButtonGroup` elements
<img width="1436" alt="Screen Shot 2020-09-14 at 16 17 05" src="https://user-images.githubusercontent.com/26746668/93067740-d01fc080-f6a5-11ea-8d1c-bc5772a0f088.png">

<img width="1433" alt="Screen Shot 2020-09-14 at 16 17 11" src="https://user-images.githubusercontent.com/26746668/93067783-da41bf00-f6a5-11ea-8a9e-d48def6ee186.png">

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-09-14 09:54 UTC, nphivu414 commented on packages/elements-next/src/components/button/button.mdx
> +## Document
Please change to `## Properties`

2020-09-14 09:56 UTC, nphivu414 commented on packages/elements-next/src/components/button/button.mdx
> +# Button
Please add a description for Button
```
# Button
The button is an essential element of any design. It's meant to look and behave as an interactive element of your page.
```

2020-09-14 10:35 UTC, nphivu414 requested changes

2020-09-14 10:35 UTC, nphivu414 commented on packages/elements-next/src/components/button/button.tsx
> +  children?: React.ReactNode
No need to define `children` prop here

2020-09-15 05:27 UTC, tanphamhaiduong approved these changes
LGTM

2020-09-15 06:47 UTC, nphivu414 approved these changes

2020-09-15 06:59 UTC, merged