bugfix: various app-builder issues
reapit/foundations pull request #5055
Opened 2021-09-20 16:40 UTC by joshbalfour

# Pull request checklist

**Detail as per issue below (required):**

fixes: #

2021-09-20 20:20 UTC, willmcvay requested changes

2021-09-20 20:20 UTC, willmcvay commented on packages/app-builder-backend/src/eject/templates/format.ts
> +  const baseEslint = require('@reapit/ts-scripts/src/eslint/base-eslint') // inline import because ts-scripts has dependency issues
Think this is just because you need to have the eslint executable in scope in your package - can explain in the morning!

2021-09-20 20:20 UTC, willmcvay commented on packages/ts-scripts/src/webpack/webpack.config.dev.js
> +const webpackConfigDev = ({ appName }) => {
Feels a bit scary because this is used by all the things - bit hard to follow what changed - can you just fill me in in the morning please? Ta!

2021-09-24 09:43 UTC, bashleigh approved these changes
Only one small suggestion

2021-09-24 09:43 UTC, bashleigh commented on packages/app-builder-backend/src/eject/templates/app.ts
> +      uri: 'http://localhost:4000/graphql/',
use an env here instead?

2021-09-24 09:55 UTC, joshbalfour commented on packages/app-builder-backend/src/eject/templates/app.ts
> +      uri: 'http://localhost:4000/graphql/',
good shout!

2021-09-24 10:41 UTC, willmcvay approved these changes
LGTM 👍🏻

2021-09-24 10:42 UTC, merged