feat: added app v8 edit page
reapit/foundations pull request #5533
Opened 2021-11-18 17:16 UTC by bashleigh

# Pull request checklist

**Detail as per issue below (required):**

fixes: #

2021-11-18 18:01 UTC, joshbalfour approved these changes

2021-11-19 09:47 UTC, willmcvay requested changes

2021-11-19 09:47 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/app-detail-v8-edit.tsx
> +import React, { useState } from 'react'
Can you add a test file please? Thanks :-)

2021-11-23 14:01 UTC, willmcvay approved these changes

2021-11-23 14:07 UTC, merged