feat: deployment pusher impelementation
reapit/foundations pull request #5710
Opened 2021-12-16 10:44 UTC by bashleigh

# Pull request checklist

**Detail as per issue below (required):**

fixes: #

2021-12-16 10:56 UTC, willmcvay requested changes

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +const PipelineInfo = ({ pipeline }: { pipeline: PipelineModelInterface }) => {
Can you add a type here please ie `FC<SomeProps`

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +const PipelineDeploymentTable = ({
As above, can you add a type. Also, can you break this component into a separate file please

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +const PipelineInfo = ({ pipeline }: { pipeline: PipelineModelInterface }) => {
Also, needs a test

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +          <BodyText>{pipeline.subDomain ? `https://${pipeline.subDomain}.dev.paas.reapit.cloud` : ''}</BodyText>
What happens in prod? The dev.paas bit should come from the config so we can switch it for prod.paas

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +  useEffect(() => {
Can you break the useEffect functions into handlers and add tests please

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/deployment-info.tsx
> +export const PipelineDeploymentInfo = ({ pipeline, channel }: { pipeline: PipelineModelInterface; channel: any }) => {
As above, separate component, add a type and tests

2021-12-16 10:56 UTC, willmcvay commented on packages/developer-portal/src/components/pages/v8/pipeline/index.tsx
> +const PipelineWrapper = ({
And again for these two components, can you break out the logic, break into separate components, add tests and props types please

2021-12-16 10:56 UTC, willmcvay commented on packages/utils-react/src/use-reapit-data/use-reapit-update.ts
> +    console.log('starting')
Do you need this console?

2021-12-16 10:56 UTC, willmcvay commented on packages/utils-react/src/use-reapit-data/use-reapit-update.ts
> +      if (!returnUpdatedModel && !returnUpdatedModelWithLocation) await setLoading(false)
There really is a lot of logic in here - is there a way to break it out into something more maintainable / testable? I am just thinking it's something we will use all over the place and feels a bit fragile / complex

2021-12-16 16:15 UTC, joshbalfour approved these changes

2021-12-16 16:22 UTC, bashleigh commented
Needs live urls though (!)

2022-01-04 08:18 UTC, willmcvay approved these changes
Changes look better, can you rebase and get it merged in please :-)

2022-01-04 10:17 UTC, merged